#!/usr/bin/env python3
"""Build the bilingual project documentation as a self-contained static site."""

from __future__ import annotations

import argparse
import html
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
import posixpath
import shutil
import sys
import tempfile
from urllib.parse import quote, unquote, urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.validate import DOC_PAIRS  # noqa: E402

import markdown  # noqa: E402
from markdown.extensions import Extension  # noqa: E402
from markdown.treeprocessors import Treeprocessor  # noqa: E402


GITHUB_ROOT = "https://github.com/AoiOTA/Kiss-My-Agent"
MARKER_NAME = ".kiss-my-agent-pages"
MARKER_CONTENT = "generated by scripts/build_site.py\n"
LANGUAGES = ("en", "zh-CN")
NAV_LABELS = {
    "en": (
        "Home",
        "Contributing",
        "Security",
        "Installation",
        "Configuration",
        "Extending",
        "FAQ",
        "Testing",
    ),
    "zh-CN": ("首页", "贡献", "安全", "安装", "配置", "扩展", "常见问题", "测试"),
}
BODY_ATTRIBUTES = {
    "a": {"aria-current", "class", "href", "hreflang", "id", "title"},
    "abbr": {"title"},
    "blockquote": set(),
    "br": set(),
    "code": {"class"},
    "dd": set(),
    "del": set(),
    "div": {"align", "class", "id"},
    "dl": set(),
    "dt": set(),
    "em": set(),
    "h1": {"id"},
    "h2": {"id"},
    "h3": {"id"},
    "h4": {"id"},
    "h5": {"id"},
    "h6": {"id"},
    "hr": set(),
    "img": {"alt", "class", "height", "src", "title", "width"},
    "li": {"value"},
    "ol": {"start"},
    "p": {"class"},
    "pre": set(),
    "strong": set(),
    "sup": {"id"},
    "table": set(),
    "tbody": set(),
    "td": {"align"},
    "th": {"align"},
    "thead": set(),
    "tr": set(),
    "ul": set(),
}
PAGE_ATTRIBUTES = BODY_ATTRIBUTES | {
    "article": {"class"},
    "body": set(),
    "head": set(),
    "header": {"class"},
    "html": {"lang"},
    "link": {"href", "hreflang", "rel"},
    "main": {"id", "tabindex"},
    "meta": {"charset", "content", "name"},
    "nav": {"aria-label", "class"},
    "title": set(),
}
URL_ATTRIBUTES = {"href", "src"}
SAFE_URL_SCHEMES = {"http", "https", "mailto", "tel"}


class BuildError(RuntimeError):
    """The documentation site cannot be built without a broken result."""


class SafeHTMLParser(HTMLParser):
    """Reject markup outside the small HTML surface used by the generated site."""

    def __init__(self, context: str, full_page: bool) -> None:
        super().__init__(convert_charrefs=True)
        self.context = context
        self.allowed = PAGE_ATTRIBUTES if full_page else BODY_ATTRIBUTES

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        allowed_attributes = self.allowed.get(tag)
        if allowed_attributes is None:
            raise BuildError(f"unsafe HTML tag <{tag}> in {self.context}")
        for raw_name, value in attrs:
            name = raw_name.lower()
            if name.startswith("on"):
                raise BuildError(f"unsafe event attribute {name} in {self.context}")
            if name == "style":
                raise BuildError(f"unsafe style attribute in {self.context}")
            if name not in allowed_attributes:
                raise BuildError(f"HTML attribute {name} is not allowed on <{tag}> in {self.context}")
            if name in URL_ATTRIBUTES and value is not None:
                validate_url(value, self.context)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)


def validate_url(value: str, context: str) -> None:
    decoded = unquote(value)
    compact = "".join(character for character in decoded if ord(character) > 32)
    if compact.startswith("//"):
        raise BuildError(f"scheme-relative URL is not allowed in {context}: {value}")
    parts = urlsplit(compact)
    scheme = parts.scheme.lower()
    if scheme and scheme not in SAFE_URL_SCHEMES:
        raise BuildError(f"unsafe URL scheme {scheme} in {context}: {value}")


def validate_safe_html(markup: str, context: str, *, full_page: bool) -> None:
    parser = SafeHTMLParser(context, full_page)
    parser.feed(markup)
    parser.close()


def ensure_replaceable_output(output: Path) -> None:
    """Allow only a new, empty, or recognizably generated output directory."""
    if output.resolve() == ROOT or output.is_symlink():
        raise BuildError("output must be a normal directory distinct from the repository root")
    if not output.exists():
        return
    if not output.is_dir():
        raise BuildError(f"output exists and is not a directory: {output}")
    if not any(output.iterdir()):
        return
    marker = output / MARKER_NAME
    if marker.is_symlink() or not marker.is_file():
        raise BuildError(f"refusing to replace non-empty unmarked output directory: {output}")
    try:
        marker_content = marker.read_text(encoding="utf-8")
    except UnicodeError as error:
        raise BuildError(f"invalid generated output marker: {marker}") from error
    if marker_content != MARKER_CONTENT:
        raise BuildError(f"refusing to replace non-empty unmarked output directory: {output}")


def document_routes(
    pairs: tuple[tuple[str, str], ...] = DOC_PAIRS,
) -> tuple[dict[str, str], dict[str, str]]:
    """Return source-to-route and source-to-counterpart mappings."""
    routes: dict[str, str] = {}
    counterparts: dict[str, str] = {}
    claimed: dict[str, str] = {}
    for english, chinese in pairs:
        basename = Path(english).stem.lower()
        english_route = "index.html" if english == "README.md" else f"{basename}.html"
        chinese_route = (
            "zh-CN/index.html"
            if chinese == "README.zh-CN.md"
            else f"zh-CN/{basename}.html"
        )
        for source, route in ((english, english_route), (chinese, chinese_route)):
            collision_key = route.casefold()
            previous = claimed.get(collision_key)
            if previous is not None:
                raise BuildError(f"route collision: {previous} and {source} both map to {route}")
            claimed[collision_key] = source
            routes[source] = route
        counterparts[english] = chinese
        counterparts[chinese] = english
    return routes, counterparts


def relative_site_url(current_route: str, target_route: str) -> str:
    current_parent = str(PurePosixPath(current_route).parent)
    return posixpath.relpath(target_route, current_parent)


class LinkRewriter:
    """Resolve a Markdown document link against the repository and site routes."""

    def __init__(self, source: str, route: str, routes: dict[str, str]) -> None:
        self.source = source
        self.route = route
        self.routes = routes

    def rewrite(self, value: str) -> str:
        parts = urlsplit(value)
        if not value or value.startswith("#") or parts.scheme or parts.netloc:
            return value
        if parts.path.startswith("/"):
            return value

        source_parent = ROOT / Path(self.source).parent
        resolved = (source_parent / unquote(parts.path)).resolve()
        try:
            relative = resolved.relative_to(ROOT).as_posix()
        except ValueError as error:
            raise BuildError(f"link escapes repository in {self.source}: {value}") from error

        if relative in self.routes:
            path = relative_site_url(self.route, self.routes[relative])
        else:
            try:
                asset_relative = resolved.relative_to(ROOT / "assets").as_posix()
            except ValueError:
                asset_relative = None
            if asset_relative is not None and resolved.exists():
                asset_route = "assets"
                if asset_relative != ".":
                    asset_route += f"/{asset_relative}"
                path = relative_site_url(self.route, asset_route)
            else:
                if resolved.is_dir() or parts.path.endswith("/"):
                    kind = "tree"
                else:
                    kind = "blob"
                path = f"{GITHUB_ROOT}/{kind}/main/{quote(relative, safe='/._-')}"

        return urlunsplit(("", "", path, parts.query, parts.fragment))


class LinkTreeprocessor(Treeprocessor):
    def __init__(self, md: markdown.Markdown, rewriter: LinkRewriter) -> None:
        super().__init__(md)
        self.rewriter = rewriter

    def run(self, root):  # type: ignore[no-untyped-def]
        for element in root.iter():
            attribute = "href" if element.tag == "a" else "src" if element.tag == "img" else None
            if attribute is None or attribute not in element.attrib:
                continue
            original = element.attrib[attribute]
            element.attrib[attribute] = self.rewriter.rewrite(original)
            if (
                element.tag == "img"
                and unquote(urlsplit(original).path).endswith("assets/kiss-my-agent-hero.png")
            ):
                element.attrib["class"] = "hero"
        return root


class LinkRewriteExtension(Extension):
    def __init__(self, rewriter: LinkRewriter) -> None:
        self.rewriter = rewriter
        super().__init__()

    def extendMarkdown(self, md: markdown.Markdown) -> None:  # noqa: N802
        md.treeprocessors.register(LinkTreeprocessor(md, self.rewriter), "site_links", 5)


class OutputParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: set[str] = set()
        self.references: list[tuple[str, str]] = []
        self.alternates: dict[str, str] = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = {name: value for name, value in attrs if value is not None}
        if "id" in values:
            self.ids.add(values["id"])
        if tag in {"a", "link"} and "href" in values:
            self.references.append(("href", values["href"]))
        if tag in {"img", "source"} and "src" in values:
            self.references.append(("src", values["src"]))
        if tag == "link" and values.get("rel") == "alternate" and "hreflang" in values:
            self.alternates[values["hreflang"]] = values.get("href", "")


def parse_output(path: Path) -> OutputParser:
    parser = OutputParser()
    parser.feed(path.read_text(encoding="utf-8"))
    return parser


def validate_output(output: Path, routes: dict[str, str], counterparts: dict[str, str]) -> None:
    """Fail when a generated local URL, fragment, route, or counterpart is broken."""
    marker = output / MARKER_NAME
    if (
        marker.is_symlink()
        or not marker.is_file()
        or marker.read_text(encoding="utf-8") != MARKER_CONTENT
    ):
        raise BuildError(f"generated output marker is missing or invalid: {marker}")
    expected = {output / route for route in routes.values()}
    actual = set(output.glob("*.html")) | set((output / "zh-CN").glob("*.html"))
    if actual != expected:
        missing = sorted(str(path.relative_to(output)) for path in expected - actual)
        extra = sorted(str(path.relative_to(output)) for path in actual - expected)
        raise BuildError(f"generated route set differs; missing={missing}, extra={extra}")

    for path in expected:
        validate_safe_html(
            path.read_text(encoding="utf-8"),
            path.relative_to(output).as_posix(),
            full_page=True,
        )
    parsed = {path: parse_output(path) for path in expected}
    output_root = output.resolve()
    for page, data in parsed.items():
        for attribute, value in data.references:
            parts = urlsplit(value)
            if parts.scheme or parts.netloc:
                continue
            target = page if not parts.path else (page.parent / unquote(parts.path)).resolve()
            try:
                target.relative_to(output_root)
            except ValueError as error:
                raise BuildError(f"local {attribute} escapes output in {page.name}: {value}") from error
            if not target.exists():
                raise BuildError(f"broken local {attribute} in {page.relative_to(output)}: {value}")
            if parts.fragment:
                if not target.is_file() or target.suffix != ".html":
                    raise BuildError(f"fragment targets non-HTML resource in {page.name}: {value}")
                target_data = parsed.get(target)
                if target_data is None:
                    target_data = parse_output(target)
                fragment = unquote(parts.fragment)
                if fragment not in target_data.ids:
                    raise BuildError(f"missing fragment #{fragment} in {target.relative_to(output)}")

    for source, counterpart in counterparts.items():
        page = output / routes[source]
        target_route = routes[counterpart]
        target_language = "zh-CN" if counterpart.endswith(".zh-CN.md") else "en"
        expected_href = relative_site_url(routes[source], target_route)
        if parsed[page].alternates.get(target_language) != expected_href:
            raise BuildError(f"missing language counterpart from {routes[source]} to {target_route}")


def page_language(source: str) -> str:
    return "zh-CN" if source.endswith(".zh-CN.md") else "en"


def page_title(body: str, source: str) -> str:
    parser = _TitleParser()
    parser.feed(body)
    return parser.title or Path(source).stem.replace(".zh-CN", "")


class _TitleParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.in_h1 = False
        self.parts: list[str] = []
        self.title = ""

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "h1" and not self.title:
            self.in_h1 = True

    def handle_endtag(self, tag: str) -> None:
        if tag == "h1" and self.in_h1:
            self.title = "".join(self.parts).strip()
            self.in_h1 = False

    def handle_data(self, data: str) -> None:
        if self.in_h1:
            self.parts.append(data)


def render_nav(source: str, route: str, routes: dict[str, str], language: str) -> str:
    items: list[str] = []
    language_index = LANGUAGES.index(language)
    nav_sources = (pair[language_index] for pair in DOC_PAIRS)
    for nav_source, label in zip(nav_sources, NAV_LABELS[language], strict=True):
        href = relative_site_url(route, routes[nav_source])
        current = ' aria-current="page"' if nav_source == source else ""
        items.append(
            f'<a href="{html.escape(href, quote=True)}"{current}>{html.escape(label)}</a>'
        )
    return "\n".join(items)


def render_markdown(text: str, source: str, route: str, routes: dict[str, str]) -> str:
    rewriter = LinkRewriter(source, route, routes)
    body = markdown.markdown(
        text,
        extensions=["extra", "sane_lists", LinkRewriteExtension(rewriter)],
        output_format="html5",
    )
    validate_safe_html(body, source, full_page=False)
    return body


def render_page(
    template: str,
    source: str,
    body: str,
    routes: dict[str, str],
    counterparts: dict[str, str],
) -> str:
    route = routes[source]
    language = page_language(source)
    counterpart = counterparts[source]
    counterpart_language = page_language(counterpart)
    counterpart_href = relative_site_url(route, routes[counterpart])
    stylesheet_href = relative_site_url(route, "assets/style.css")
    labels = {
        "en": ("Skip to content", "Primary navigation", "简体中文"),
        "zh-CN": ("跳到正文", "主导航", "English"),
    }[language]
    replacements = {
        "lang": language,
        "title": html.escape(page_title(body, source)),
        "content_class": (
            "content home-content"
            if source in {"README.md", "README.zh-CN.md"}
            else "content"
        ),
        "stylesheet_href": html.escape(stylesheet_href, quote=True),
        "counterpart_lang": counterpart_language,
        "counterpart_href": html.escape(counterpart_href, quote=True),
        "skip_label": labels[0],
        "nav_label": labels[1],
        "language_label": labels[2],
        "nav": render_nav(source, route, routes, language),
        "body": body,
    }
    rendered = template
    for key, value in replacements.items():
        rendered = rendered.replace("{{" + key + "}}", value)
    validate_safe_html(rendered, routes[source], full_page=True)
    return rendered


def build(output: Path) -> None:
    routes, counterparts = document_routes()
    output = output.expanduser().absolute()
    ensure_replaceable_output(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    template = (ROOT / "site/template.html").read_text(encoding="utf-8")

    with tempfile.TemporaryDirectory(prefix=f".{output.name}-", dir=output.parent) as temporary:
        stage = Path(temporary)
        shutil.copytree(ROOT / "assets", stage / "assets")
        shutil.copy2(ROOT / "site/style.css", stage / "assets/style.css")
        (stage / MARKER_NAME).write_text(MARKER_CONTENT, encoding="utf-8")

        for source, route in routes.items():
            body = render_markdown(
                (ROOT / source).read_text(encoding="utf-8"),
                source,
                route,
                routes,
            )
            destination = stage / route
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(
                render_page(template, source, body, routes, counterparts),
                encoding="utf-8",
            )

        validate_output(stage, routes, counterparts)
        ensure_replaceable_output(output)
        if output.exists():
            shutil.rmtree(output)
        stage.rename(output)

    print(f"built {len(routes)} pages in {output}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "_site",
        help="generated site directory (default: repository _site)",
    )
    return parser.parse_args()


def main() -> int:
    build(parse_args().output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
